### PR TITLE
Fix parent selection

### PR DESCRIPTION
**Pull request by peskdale**
Fixes script incorrectly grabbing the profile image instead of the post image. Seems IG have moved the post text one layer deeper than it used to be.

### CODE REVIEW

**Review by HamedEmine — CHANGES_REQUESTED** [review]
Hi,

This worked for me instead:
const parent = this.closest(".eo2As").parentNode.parentNode.previousElementSibling

**Comment by peskdale** [comment]
> Hi,
> 
> This worked for me instead:
> const parent = this.closest(".eo2As").parentNode.parentNode.previousElementSibling

Agreed. My code was definitely working the other day, but it seems IG have added yet another layer since I opened the PR.

**Comment by pierrejolly** [comment]
Thank for the fix, @HayaoGai can you merge ?

**Review by HamedEmine — CHANGES_REQUESTED** [review]
They updated something that broke the script again

New working line 84:
const parent = this.closest(".eo2As").parentNode.parentNode.parentNode.previousElementSibling;

**Comment by pierrejolly** [comment]
They rolled back to:

`const parent = this.closest(".eo2As").parentNode.parentNode.previousElementSibling;` 🤯

**Pull request closed without merging**
